PracticaMvcCore2Acl/Controllers/LibrosController.cs
using System.Security.Claims;
using Microsoft.AspNetCore.Mvc;
using PracticaMvcCore2Acl.Extensions;
using PracticaMvcCore2Acl.Filters;
using PracticaMvcCore2Acl.Models;
using PracticaMvcCore2Acl.Repositories;

namespace PracticaMvcCore2Acl.Controllers
{
    public class LibrosController : Controller
    {
        private RepositoryLibros repo;

        public LibrosController(RepositoryLibros repo)
        {
            this.repo = repo;
        }

        public async Task<IActionResult> Index()
        {
            List<Libro> libros = await this.repo.GetLibrosAsync();
            return View(libros);
        }

        public async Task<IActionResult> GeneroLibros(int idgenero)
        {
            List<Libro> libros = await this.repo.GetLibrosGeneroAsync(idgenero);
            return View(libros);
        }

        public async Task<IActionResult> DetalleLibro(int idlibro)
        {
            Libro libro = await this.repo.FindLibroAsync(idlibro);
            return View(libro);
        }

        public async Task<IActionResult> AddCarrito(int idlibro)
        {
            var carritoIds = HttpContext.Session.GetObject<List<int>>("CarritoIds");
            if (carritoIds == null)
            {
                carritoIds = new List<int>();
            }

            carritoIds.Add(idlibro);
            HttpContext.Session.SetObject("CarritoIds", carritoIds);

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> RemoveCarrito(int idlibro)
        {
            var carritoIds = HttpContext.Session.GetObject<List<int>>("CarritoIds");

            if (carritoIds.Contains(idlibro))
            {
                carritoIds.Remove(idlibro);
            }

            if (carritoIds.Count > 0)
            {
                HttpContext.Session.SetObject("CarritoIds", carritoIds);
            }
            else
            {
                HttpContext.Session.Remove("CarritoIds");
            }

            return RedirectToAction("Carrito");
        }

        public async Task<IActionResult> Carrito()
        {
            var carritoIds = HttpContext.Session.GetObject<List<int>>("CarritoIds");
            if (carritoIds == null)
            {
                carritoIds = new List<int>();
            }

            List<Libro> libros = await this.repo.FindLibrosCarritoAsync(carritoIds);

            return View(libros);
        }

        [AuthorizeUsuario]
        public async Task<IActionResult> Finalizar()
        {
            var carritoIds = HttpContext.Session.GetObject<List<int>>("CarritoIds");
            if (carritoIds == null)
            {
                carritoIds = new List<int>();
            }

            await this.repo.FinalizarCompraLibrosAsync(carritoIds, int.Parse(HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value));

            HttpContext.Session.Remove("CarritoIds");

            return RedirectToAction("ComprasUsuario");
        }

        [AuthorizeUsuario]
        public async Task<IActionResult> Perfil()
        {
            return View();
        }

        [AuthorizeUsuario]
        public async Task<IActionResult> ComprasUsuario()
        {
            List<VistaPedido> pedidosUser = await this.repo.GetComprasUsuarioAsync(int.Parse(HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value));
            return View(pedidosUser);
        }
    }
}

PracticaMvcCore2Acl/ViewComponents/GenerosViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using PracticaMvcCore2Acl.Models;
using PracticaMvcCore2Acl.Repositories;

namespace PracticaMvcCore2Acl.ViewComponents
{
    public class GenerosViewComponent: ViewComponent
    {
        private RepositoryLibros repo;

        public GenerosViewComponent(RepositoryLibros repo)
        {
            this.repo = repo;
        }

        public async Task <IViewComponentResult> InvokeAsync()
        {
            List<Genero> generos = await this.repo.GetGenerosAsync();
            return View("Default", generos);
        }
    }
}

PracticaMvcCore2Acl/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PracticaMvcCore2Acl</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PracticaMvcCore2Acl.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PracticaMvcCore2Acl</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @*  <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li> *@
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Libros" asp-action="Index">Libros</a>
                        </li>

                        @await Component.InvokeAsync("Generos")

                        <partial name="_MenuUsuario"/>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - PracticaMvcCore2Acl - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

PracticaMvcCore2Acl/Views/Shared/_MenuUsuario.cshtml
@{
    var carritoIds = Context.Session.GetObject<List<int>>("CarritoIds") ?? new List<int>();
    var numProductos = carritoIds.Count;
}

<li class="nav-item">
    <a asp-controller="Libros"
       asp-action="Carrito"
       class="nav-link">
        Carrito: @numProductos
    </a>
</li>

@if (!Context.User.Identity.IsAuthenticated)
{
    <li class="nav-item">
        <a asp-controller="Managed"
           asp-action="Login"
           class="nav-link">
            Login
        </a>
    </li>
}
else
{
    <li class="nav-item">
        <a asp-controller="Libros"
           asp-action="Perfil"
           class="nav-link">
            <img src="~/images/@Context.User.FindFirst("Foto").Value" width="20" class="rounded-5"/>
            Hola, @Context.User.FindFirst("Nombre").Value
        </a>
    </li>
   @*  <li class="nav-item">
        <a class="nav-link" asp-controller="Libros" asp-action="ComprasUsuario">Pedidos</a>
    </li> *@
    <li class="nav-item">
        <a asp-controller="Managed"
           asp-action="Logout"
           class="nav-link">
            Cerrar sesión
        </a>
    </li>
}